#!/usr/bin/env python3
"""
Tailscale ACL Combiner

Combines modular ACL files from production or development directories
into a single policy.hujson file for deployment to Tailscale.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Any


def load_json_file(file_path: Path) -> Dict[str, Any]:
    """Load and parse a JSON file."""
    try:
        with open(file_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Warning: {file_path} not found, skipping", file=sys.stderr)
        return {}
    except json.JSONDecodeError as e:
        print(f"Error parsing {file_path}: {e}", file=sys.stderr)
        sys.exit(1)


def combine_acl_files(environment: str, base_dir: Path) -> Dict[str, Any]:
    """
    Combine ACL files from the specified environment directory.

    Args:
        environment: Either 'production' or 'development'
        base_dir: Base directory containing the environment subdirectories

    Returns:
        Combined policy dictionary
    """
    env_dir = base_dir / environment

    if not env_dir.exists():
        print(f"Error: Environment directory '{env_dir}' does not exist", file=sys.stderr)
        sys.exit(1)

    # Load each component file
    groups_data = load_json_file(env_dir / "groups.json")
    ipsets_data = load_json_file(env_dir / "ipsets.json")
    posture_data = load_json_file(env_dir / "posture.json")

    # Combine into a single policy structure
    combined = {}

    # Add groups and tagOwners from groups.json
    if "groups" in groups_data:
        combined["groups"] = groups_data["groups"]
    if "tagOwners" in groups_data:
        combined["tagOwners"] = groups_data["tagOwners"]

    # Add hosts from ipsets.json
    if "hosts" in ipsets_data:
        combined["hosts"] = ipsets_data["hosts"]

    # Add postures from posture.json
    if "postures" in posture_data:
        combined["postures"] = posture_data["postures"]

    return combined


def read_current_policy(policy_file: Path) -> Dict[str, Any]:
    """
    Read the current policy.hujson file and extract sections we want to preserve.
    This includes grants, ssh, autoApprovers, etc. that aren't in the modular files.
    """
    if not policy_file.exists():
        return {}

    try:
        with open(policy_file, 'r') as f:
            content = f.read()

        # Simple parsing: remove comments and parse as JSON
        import re
        # Remove // comments
        content = re.sub(r'//[^\n]*', '', content)
        # Remove /* */ comments
        content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
        # Remove trailing commas
        content = re.sub(r',(\s*[}\]])', r'\1', content)

        return json.loads(content)
    except Exception as e:
        print(f"Warning: Could not parse existing policy.hujson: {e}", file=sys.stderr)
        return {}


def format_as_hujson(data: Dict[str, Any], indent: int = 2) -> str:
    """
    Format the policy data as HuJSON (JSON with comments).
    """
    lines = []
    lines.append("// Tailscale ACL Policy")
    lines.append("// Generated by tailscale-acl-combiner")
    lines.append("// DO NOT EDIT DIRECTLY - Edit files in production/ or development/ directories")
    lines.append("{")

    # Preserve specific keys in order: grants, ssh, then the combined sections
    preserved_keys = ["grants", "ssh", "autoApprovers"]
    combined_keys = ["groups", "tagOwners", "hosts", "postures"]

    def format_value(v, level=1):
        """Recursively format a value with proper indentation."""
        indent_str = "  " * level
        if isinstance(v, dict):
            if not v:
                return "{}"
            lines = ["{"]
            for i, (k, val) in enumerate(v.items()):
                comma = "," if i < len(v) - 1 else ""
                formatted_val = format_value(val, level + 1)
                lines.append(f'{indent_str}  "{k}": {formatted_val}{comma}')
            lines.append(f"{indent_str}}}")
            return "\n".join(lines)
        elif isinstance(v, list):
            if not v:
                return "[]"
            lines = ["["]
            for i, item in enumerate(v):
                comma = "," if i < len(v) - 1 else ""
                formatted_item = format_value(item, level + 1)
                if isinstance(item, (dict, list)) and len(str(item)) > 50:
                    lines.append(f"{indent_str}  {formatted_item}{comma}")
                else:
                    lines.append(f"{indent_str}  {formatted_item}{comma}")
            lines.append(f"{indent_str}]")
            return "\n".join(lines)
        elif isinstance(v, str):
            return f'"{v}"'
        elif isinstance(v, bool):
            return "true" if v else "false"
        elif v is None:
            return "null"
        else:
            return str(v)

    # Add preserved sections first
    sections_added = 0
    for key in preserved_keys:
        if key in data:
            if sections_added > 0:
                lines.append("")
            comment_map = {
                "grants": "// Access control rules",
                "ssh": "// Tailscale SSH rules",
                "autoApprovers": "// Auto-approve subnet routes and exit nodes"
            }
            if key in comment_map:
                lines.append(f"  {comment_map[key]}")
            formatted = format_value(data[key], 1)
            lines.append(f'  "{key}": {formatted},')
            sections_added += 1

    # Add combined sections
    for key in combined_keys:
        if key in data:
            if sections_added > 0:
                lines.append("")
            comment_map = {
                "groups": "// User and device groups",
                "tagOwners": "// Tag ownership definitions",
                "hosts": "// Named IP ranges and hosts",
                "postures": "// Device posture requirements"
            }
            if key in comment_map:
                lines.append(f"  {comment_map[key]}")
            formatted = format_value(data[key], 1)
            # Remove trailing comma from last item
            if key == combined_keys[-1] or key == [k for k in combined_keys if k in data][-1]:
                lines.append(f'  "{key}": {formatted}')
            else:
                lines.append(f'  "{key}": {formatted},')
            sections_added += 1

    lines.append("}")
    return "\n".join(lines)


def main():
    """Main execution function."""
    if len(sys.argv) != 2:
        print("Usage: combine.py <environment>", file=sys.stderr)
        print("  environment: 'production' or 'development'", file=sys.stderr)
        sys.exit(1)

    environment = sys.argv[1].lower()
    if environment not in ['production', 'development']:
        print(f"Error: Invalid environment '{environment}'. Must be 'production' or 'development'", file=sys.stderr)
        sys.exit(1)

    # Determine paths
    script_dir = Path(__file__).parent
    base_dir = script_dir
    policy_file = script_dir.parent / "policy.hujson"

    print(f"Combining ACL files from '{environment}' environment...")

    # Read existing policy to preserve grants, ssh, etc.
    existing_policy = read_current_policy(policy_file)

    # Combine modular files
    combined_sections = combine_acl_files(environment, base_dir)

    # Merge: preserve existing sections, update with combined sections
    final_policy = existing_policy.copy()
    final_policy.update(combined_sections)

    # Write to policy.hujson
    output = format_as_hujson(final_policy)
    policy_file.write_text(output + "\n")

    print(f"✓ Successfully wrote combined policy to {policy_file}")
    print(f"  - Environment: {environment}")
    print(f"  - Groups: {len(combined_sections.get('groups', {}))}")
    print(f"  - Tag Owners: {len(combined_sections.get('tagOwners', {}))}")
    print(f"  - Hosts: {len(combined_sections.get('hosts', {}))}")
    print(f"  - Postures: {len(combined_sections.get('postures', {}))}")


if __name__ == "__main__":
    main()
